- name: Swarm Init
  command: sudo docker swarm init --advertise-addr {{ inventory_hostname }}
  run_once: true

- name: Manager Token
  command: sudo docker swarm join-token manager -q
  register: manager_token
  run_once: true

- name: Show Manger Token
  debug: var=manager_token.stdout
  run_once: true