metadata:
  name: "mosquitto"
  namespace:
  labels:
    app: "mosquitto"
spec:
  replicas: 2
  selector:
    match_labels:
      app: "mosquitto"
  template:
    metadata:
      labels:
        app: "mosquitto"
    spec:
      container:
        name: "mosquitto"
        image: "eclipse-mosquitto:1.6.2"
        port:
          container_port: 1883
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "50Mi"
        volume_mount:
          mount_path: /mosquitto/config
          name: mosquitto
      volume:
        name: mosquitto
        config_map:
          name: mosquito-config-file
