version: "3"
services:
  pg_master:
    image: mesoform/pg10master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
      - PG_REP_USER=testrep
      - PG_REP_PASSWORD=123456
      - HBA_ADDRESS=0.0.0.0/0
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - pg_cluster
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
        - node.role == manager
  pg_slave:
    image: mesoform/pg10slave
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
      - PG_REP_USER=testrep
      - PG_REP_PASSWORD=123456
      - PG_MASTER_HOST=       # This needs to be the swarm node private IP instead of the service name (pg_master) which resolves to the service IP
      - HBA_ADDRESS=0.0.0.0/0
    networks:
      default:
        aliases:
          - pg_cluster
    deploy:
      placement:
        constraints:
        - node.labels.type != primary
        - node.role == manager
networks:
  default:

volumes:
  pg_data:
