metadata:
  annotations:
    key1:
    key2:
  name: "nginx-deploy-example"
  namespace:
  labels:
    env: "test"
  generate_name:
spec:
  min_ready_seconds:
  paused:
  progress_deadline_seconds:
  replicas: 2
  revision_history_limit:
  strategy:
    type: RollingUpdate
    rolling_update:
      max_surge:
      max_unavailable:
  selector:
    match_labels:
      app: "Nginx"
  template:
    metadata:
      labels:
        app: "Nginx"
    spec:
      automount_service_account_token:
      container:
        name: "nginx-example"
        image: "nginx:1.7.8"
        port:
          container_port: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "50Mi"
        liveness_probe:
          initial_delay_seconds: 3
          period_seconds: 3
          timeout_seconds: 4
wait_for_rollout:
